-- Recreated 2026-08-24 with SQL SECURITY INVOKER so the views
-- run as the querying user instead of a hardcoded definer that only
-- exists on the production server. Logic is unchanged.

CREATE OR REPLACE SQL SECURITY INVOKER VIEW `training_all` AS
select `phnportalenterto_trms`.`training`.`id` AS `id`,`phnportalenterto_trms`.`training`.`trainingcode` AS `trainingcode`,`phnportalenterto_trms`.`training`.`title` AS `title`,`phnportalenterto_trms`.`training`.`program` AS `program`,`phnportalenterto_trms`.`training`.`cost` AS `cost`,`phnportalenterto_trms`.`training`.`platform` AS `platform`,`phnportalenterto_trms`.`training`.`function` AS `function`,`phnportalenterto_trms`.`training`.`startdate` AS `startdate`,`phnportalenterto_trms`.`training`.`enddate` AS `enddate`,`phnportalenterto_trms`.`training`.`starttime` AS `starttime`,`phnportalenterto_trms`.`training`.`endtime` AS `endtime`,`phnportalenterto_trms`.`training`.`venue` AS `venue`,`phnportalenterto_trms`.`training`.`trainer` AS `trainer`,`phnportalenterto_trms`.`training`.`hadc` AS `hadc` from `phnportalenterto_trms`.`training` union all select `phnportalenterto_trms`.`training_archive`.`id` AS `id`,`phnportalenterto_trms`.`training_archive`.`trainingcode` AS `trainingcode`,`phnportalenterto_trms`.`training_archive`.`title` AS `title`,`phnportalenterto_trms`.`training_archive`.`program` AS `program`,`phnportalenterto_trms`.`training_archive`.`cost` AS `cost`,`phnportalenterto_trms`.`training_archive`.`platform` AS `platform`,`phnportalenterto_trms`.`training_archive`.`function` AS `function`,`phnportalenterto_trms`.`training_archive`.`startdate` AS `startdate`,`phnportalenterto_trms`.`training_archive`.`enddate` AS `enddate`,`phnportalenterto_trms`.`training_archive`.`starttime` AS `starttime`,`phnportalenterto_trms`.`training_archive`.`endtime` AS `endtime`,`phnportalenterto_trms`.`training_archive`.`venue` AS `venue`,`phnportalenterto_trms`.`training_archive`.`trainer` AS `trainer`,`phnportalenterto_trms`.`training_archive`.`hadc` AS `hadc` from `phnportalenterto_trms`.`training_archive`;

CREATE OR REPLACE SQL SECURITY INVOKER VIEW `ojt_all` AS
select `phnportalenterto_trms`.`ojt`.`id` AS `id`,`phnportalenterto_trms`.`ojt`.`trainingcode` AS `trainingcode`,`phnportalenterto_trms`.`ojt`.`title` AS `title`,`phnportalenterto_trms`.`ojt`.`startdate` AS `startdate`,`phnportalenterto_trms`.`ojt`.`enddate` AS `enddate`,`phnportalenterto_trms`.`ojt`.`starttime` AS `starttime`,`phnportalenterto_trms`.`ojt`.`endtime` AS `endtime`,`phnportalenterto_trms`.`ojt`.`venue` AS `venue`,`phnportalenterto_trms`.`ojt`.`trainertype` AS `trainertype`,`phnportalenterto_trms`.`ojt`.`trainername` AS `trainername`,`phnportalenterto_trms`.`ojt`.`totalday` AS `totalday`,`phnportalenterto_trms`.`ojt`.`totalhour` AS `totalhour`,`phnportalenterto_trms`.`ojt`.`totalman` AS `totalman` from `phnportalenterto_trms`.`ojt` union all select `phnportalenterto_trms`.`ojt_archive`.`id` AS `id`,`phnportalenterto_trms`.`ojt_archive`.`trainingcode` AS `trainingcode`,`phnportalenterto_trms`.`ojt_archive`.`title` AS `title`,`phnportalenterto_trms`.`ojt_archive`.`startdate` AS `startdate`,`phnportalenterto_trms`.`ojt_archive`.`enddate` AS `enddate`,`phnportalenterto_trms`.`ojt_archive`.`starttime` AS `starttime`,`phnportalenterto_trms`.`ojt_archive`.`endtime` AS `endtime`,`phnportalenterto_trms`.`ojt_archive`.`venue` AS `venue`,`phnportalenterto_trms`.`ojt_archive`.`trainertype` AS `trainertype`,`phnportalenterto_trms`.`ojt_archive`.`trainername` AS `trainername`,`phnportalenterto_trms`.`ojt_archive`.`totalday` AS `totalday`,`phnportalenterto_trms`.`ojt_archive`.`totalhour` AS `totalhour`,`phnportalenterto_trms`.`ojt_archive`.`totalman` AS `totalman` from `phnportalenterto_trms`.`ojt_archive`;

CREATE OR REPLACE SQL SECURITY INVOKER VIEW `participation_all` AS
select `phnportalenterto_trms`.`participation`.`id` AS `id`,`phnportalenterto_trms`.`participation`.`trainingid` AS `trainingid`,`phnportalenterto_trms`.`participation`.`userid` AS `userid`,`phnportalenterto_trms`.`participation`.`attendance` AS `attendance`,`phnportalenterto_trms`.`participation`.`q1` AS `q1`,`phnportalenterto_trms`.`participation`.`q2` AS `q2`,`phnportalenterto_trms`.`participation`.`q3` AS `q3`,`phnportalenterto_trms`.`participation`.`q4` AS `q4`,`phnportalenterto_trms`.`participation`.`q5` AS `q5`,`phnportalenterto_trms`.`participation`.`q6` AS `q6`,`phnportalenterto_trms`.`participation`.`q7` AS `q7`,`phnportalenterto_trms`.`participation`.`q8` AS `q8`,`phnportalenterto_trms`.`participation`.`q9` AS `q9`,`phnportalenterto_trms`.`participation`.`q10` AS `q10`,`phnportalenterto_trms`.`participation`.`q11` AS `q11`,`phnportalenterto_trms`.`participation`.`q12` AS `q12`,`phnportalenterto_trms`.`participation`.`q13` AS `q13`,`phnportalenterto_trms`.`participation`.`q14` AS `q14`,`phnportalenterto_trms`.`participation`.`q15` AS `q15`,`phnportalenterto_trms`.`participation`.`q16` AS `q16` from `phnportalenterto_trms`.`participation` union all select `phnportalenterto_trms`.`participation_archive`.`id` AS `id`,`phnportalenterto_trms`.`participation_archive`.`trainingid` AS `trainingid`,`phnportalenterto_trms`.`participation_archive`.`userid` AS `userid`,`phnportalenterto_trms`.`participation_archive`.`attendance` AS `attendance`,`phnportalenterto_trms`.`participation_archive`.`q1` AS `q1`,`phnportalenterto_trms`.`participation_archive`.`q2` AS `q2`,`phnportalenterto_trms`.`participation_archive`.`q3` AS `q3`,`phnportalenterto_trms`.`participation_archive`.`q4` AS `q4`,`phnportalenterto_trms`.`participation_archive`.`q5` AS `q5`,`phnportalenterto_trms`.`participation_archive`.`q6` AS `q6`,`phnportalenterto_trms`.`participation_archive`.`q7` AS `q7`,`phnportalenterto_trms`.`participation_archive`.`q8` AS `q8`,`phnportalenterto_trms`.`participation_archive`.`q9` AS `q9`,`phnportalenterto_trms`.`participation_archive`.`q10` AS `q10`,`phnportalenterto_trms`.`participation_archive`.`q11` AS `q11`,`phnportalenterto_trms`.`participation_archive`.`q12` AS `q12`,`phnportalenterto_trms`.`participation_archive`.`q13` AS `q13`,`phnportalenterto_trms`.`participation_archive`.`q14` AS `q14`,`phnportalenterto_trms`.`participation_archive`.`q15` AS `q15`,`phnportalenterto_trms`.`participation_archive`.`q16` AS `q16` from `phnportalenterto_trms`.`participation_archive`;

CREATE OR REPLACE SQL SECURITY INVOKER VIEW `participateojt_all` AS
select `phnportalenterto_trms`.`participateojt`.`id` AS `id`,`phnportalenterto_trms`.`participateojt`.`ojtid` AS `ojtid`,`phnportalenterto_trms`.`participateojt`.`userid` AS `userid`,`phnportalenterto_trms`.`participateojt`.`attendance` AS `attendance`,`phnportalenterto_trms`.`participateojt`.`q1` AS `q1`,`phnportalenterto_trms`.`participateojt`.`q2` AS `q2`,`phnportalenterto_trms`.`participateojt`.`q3` AS `q3`,`phnportalenterto_trms`.`participateojt`.`totalman` AS `totalman`,`phnportalenterto_trms`.`participateojt`.`department` AS `department`,`phnportalenterto_trms`.`participateojt`.`clerkid` AS `clerkid`,`phnportalenterto_trms`.`participateojt`.`operation` AS `operation` from `phnportalenterto_trms`.`participateojt` union all select `phnportalenterto_trms`.`participateojt_archive`.`id` AS `id`,`phnportalenterto_trms`.`participateojt_archive`.`ojtid` AS `ojtid`,`phnportalenterto_trms`.`participateojt_archive`.`userid` AS `userid`,`phnportalenterto_trms`.`participateojt_archive`.`attendance` AS `attendance`,`phnportalenterto_trms`.`participateojt_archive`.`q1` AS `q1`,`phnportalenterto_trms`.`participateojt_archive`.`q2` AS `q2`,`phnportalenterto_trms`.`participateojt_archive`.`q3` AS `q3`,`phnportalenterto_trms`.`participateojt_archive`.`totalman` AS `totalman`,`phnportalenterto_trms`.`participateojt_archive`.`department` AS `department`,`phnportalenterto_trms`.`participateojt_archive`.`clerkid` AS `clerkid`,`phnportalenterto_trms`.`participateojt_archive`.`operation` AS `operation` from `phnportalenterto_trms`.`participateojt_archive`;

